<template>
  <!-- Purely decorative — positioned absolutely against app.vue's full-width
       wrapper (not the width-constrained UContainer the page content sits
       in), so it spans edge-to-edge and sits behind AppNavbar, mirroring
       HomeDitherBackground's placement/z-index approach exactly. Uses the
       article's own dithered cover image (public/articles/<slug>/cover.png,
       or cover-light.png in light mode — see below) as a static background
       rather than an animated canvas: starts at the very top, spans full
       viewport width, and tapers off via a CSS mask gradient before the
       article body starts — same visual language as the homepage hero
       (start top, full width, fade going down), just a static image instead
       of drifting noise since the source is a pre-rendered dither, not
       something we can regenerate per-frame in the browser.

       Two image variants, CSS-toggled (dark:hidden / hidden dark:block)
       rather than a JS color-mode check — same approach as
       App/ArticleCard.vue, for the same reason: renders correctly in
       prerendered static HTML before any client JS runs, avoiding a flash
       of the wrong variant. lightImage/darkImage are computed from the
       `image` prop by filename substitution (see script below), matching
       ArticleCard.vue's derivation exactly.

       Both variants now use their own dedicated duotone (cover-light.png's
       terracotta-on-near-white, matching Home/DitherBackground.vue's own
       light-mode off-white tone) instead of the previous single shared
       cover.png alpha-composited at a boosted opacity to fake contrast on
       a white page — that workaround (opacity-65 light / opacity-55 dark,
       see git history) is gone along with the washed-out-pastel problem it
       was compensating for, since cover-light.png's near-white base
       doesn't wash out against a white page to begin with. Opacity is now
       the same in both themes. -->
  <div
    ref="bgEl"
    aria-hidden="true"
    class="pointer-events-none absolute inset-x-0 top-0 -z-10 w-full bg-cover bg-top opacity-55 dark:hidden"
    :style="{
      height: `${height}px`,
      backgroundImage: `url(${lightImage})`,
      maskImage: 'linear-gradient(to bottom, black 0%, transparent 100%)',
      WebkitMaskImage: 'linear-gradient(to bottom, black 0%, transparent 100%)',
    }"
  ></div>
  <div
    ref="bgElDark"
    aria-hidden="true"
    class="pointer-events-none absolute inset-x-0 top-0 -z-10 hidden w-full bg-cover bg-top opacity-55 dark:block"
    :style="{
      height: `${height}px`,
      backgroundImage: `url(${image})`,
      maskImage: 'linear-gradient(to bottom, black 0%, transparent 100%)',
      WebkitMaskImage: 'linear-gradient(to bottom, black 0%, transparent 100%)',
    }"
  ></div>
</template>

<script setup lang="ts">
const props = defineProps<{ image: string }>();

// Derives /articles/<slug>/cover-light.png from the `image` prop
// (/articles/<slug>/cover.png) the same way ArticleCard.vue does — every
// cover is generated by scripts/generate-cover.mjs, which always writes
// both files under that fixed name, so this holds without a second prop.
const lightImage = computed(() =>
  props.image?.replace(/cover\.png$/, "cover-light.png"),
);

const bgEl = ref<HTMLDivElement | null>(null);
const bgElDark = ref<HTMLDivElement | null>(null);
const height = ref(600);
let resizeObserver: ResizeObserver | null = null;

// Same boundary-measurement approach as HomeDitherBackground: height is
// computed at runtime to reach the [data-article-background-boundary]
// marker placed just before <ContentRenderer> in pages/articles/[slug].vue,
// so the fade always finishes before the article body starts regardless of
// title length, tag count, or viewport size.
function measureHeight() {
  const boundary = document.querySelector(
    "[data-article-background-boundary]",
  );
  if (!boundary) return;
  const rect = boundary.getBoundingClientRect();
  height.value = Math.max(200, Math.round(rect.top + window.scrollY));
}

onMounted(() => {
  measureHeight();
  resizeObserver = new ResizeObserver(() => measureHeight());
  resizeObserver.observe(document.body);
  window.addEventListener("resize", measureHeight);
});

onUnmounted(() => {
  resizeObserver?.disconnect();
  window.removeEventListener("resize", measureHeight);
});

// image prop changes (navigating between two article pages without a full
// remount) should re-measure since content length likely differs.
watch(
  () => props.image,
  () => nextTick(measureHeight),
);
</script>
