<template>
  <NuxtLink :to="article.path" class="group">
    <article
      class="from-terracotta to-porcelain-950 relative overflow-hidden rounded-xl bg-gradient-to-br"
    >
      <!-- Background image. Only rendered when the article declares a cover in
           its frontmatter: this is a static build, so a guessed path for an
           article without a cover is a hard 404 in production rather than a
           silently empty image. Articles without one fall back to the gradient
           on the wrapper above.

           Two variants, CSS-toggled (dark:hidden / hidden dark:block) rather
           than a JS color-mode check — this renders correctly in prerendered
           static HTML before any client JS runs, avoiding a flash of the
           wrong variant. article.image always points at
           /articles/<slug>/cover.png (generate-cover.mjs's fixed output
           path), so the light path is derived by string substitution rather
           than requiring a second frontmatter field per article — see
           scripts/generate-cover.mjs and scripts/backfill-cover-light.mjs
           for how cover-light.png is produced (terracotta dots recolored
           against Home/DitherBackground.vue's own light-mode off-white
           tone, keeping the two dither treatments visually consistent).

           No brightness/saturate filter on the light variant — that hack
           existed only to compensate for the old shared cover's near-black
           base looking muddy on a white page; cover-light.png's near-white
           base doesn't have that problem. Dark mode keeps the original
           unfiltered image and its existing filter classes (a no-op there,
           kept only so this diff doesn't also silently change dark mode's
           established look). -->
      <div
        v-if="article.image"
        class="absolute inset-0 z-0 bg-cover bg-center dark:hidden"
        :style="{ backgroundImage: `url(${lightImage})` }"
      ></div>
      <div
        v-if="article.image"
        class="absolute inset-0 z-0 hidden bg-cover bg-center dark:block"
        :style="{ backgroundImage: `url(${article.image})` }"
      ></div>
      <!-- Overlay -->
      <div class="absolute inset-0 z-0 bg-black/40"></div>
      <!-- Cover image credit. Most open-license sources require attribution,
           so this shows whenever the article set imageAuthor in frontmatter. -->
      <span
        v-if="article.imageAuthor"
        class="absolute right-2 bottom-2 z-10 text-[10px] text-gray-300/80"
      >
        Photo: {{ article.imageAuthor }}
      </span>
      <!-- Content -->
      <div class="relative z-10 m-8 p-4">
        <time
          class="relative z-10 order-first mb-3 flex items-center pl-3.5 text-sm text-gray-200 dark:text-gray-300"
          :datetime="article.date"
        >
          <span
            class="absolute inset-y-0 left-0 flex items-center"
            aria-hidden="true"
          >
            <span
              class="h-4 w-0.5 rounded-full bg-gray-200 dark:bg-gray-500"
            ></span>
          </span>
          {{ getReadableDate(article.date) }}
        </time>
        <h2 class="group-hover:text-primary-400 text-white dark:text-white">
          {{ article.title }}
        </h2>
        <p class="relative z-10 mt-2 text-sm text-gray-100 dark:text-gray-200">
          {{ article.description }}
        </p>
      </div>
    </article>
  </NuxtLink>
</template>

<script setup>
const props = defineProps({
  article: {
    type: Object,
    required: true,
  },
});

// Derives /articles/<slug>/cover-light.png from article.image
// (/articles/<slug>/cover.png) by substituting the filename — every cover
// is generated by scripts/generate-cover.mjs, which always writes both
// files to the same directory under that fixed name, so this holds for
// every article with a cover rather than needing a second frontmatter
// field to track it explicitly.
const lightImage = computed(() =>
  props.article.image?.replace(/cover\.png$/, "cover-light.png"),
);

const getReadableDate = (dateString) => {
  const date = new Date(dateString);
  return date.toLocaleDateString("en-US", {
    year: "numeric",
    month: "short",
    day: "numeric",
  });
};
</script>
